### ISSUE TITLE
FreeBSD Port?

### ISSUE THREAD

**Issue by Peter2121** [mrclksr/DSBMD#1]
Hi,
I'm really impressed by DSBMD/DSBMC - it works fine 'out-of-the-box'. And it works better than autofs/automountd from the base system. Why don't I see DSBMD/DSBMC in the ports tree?
Thank you!
Peter

**Comment by mrclksr** [comment]
Hi Peter,

it's really nice to read that you like it. [DSBMD](http://www.freshports.org/sysutils/dsbmd/) and [DSBMC](http://www.freshports.org/sysutils/dsbmc/) are in the ports tree.

Best regards,
Marcel
