### ISSUE TITLE
Automount ex4 and ntfs patitions from disk on boot

### ISSUE THREAD

**Issue by timsofteng** [mrclksr/DSBMD#3]
Hello. I did everyting exactly like in your guide but windows and linux partitions from my disk doesn't automount on boot.
https://forums.freebsd.org/threads/dsbmd-a-media-mounting-daemon-automounter-for-freebsd.63534/

Can you help me please?

**Comment by mrclksr** [comment]
Hi @timsofteng,

1. Can you mount your partitions manually via `dsbmc-cli -m /path/to/partition`?
2. Is `dsbmc-cli -a` running (`ps ax | grep dsbmc-cli`) ?

**Comment by timsofteng** [comment]
@mrclksr 
It don't wanna be mounted.

![image](https://user-images.githubusercontent.com/51912173/92941524-2946e480-f459-11ea-8703-00b095bebada.png)

What do I do wrong?

**Comment by mrclksr** [comment]
Run `dsbmc-cli -l` to see which devices can be mounted. E.g.:
````
% dsbmc-cli -l
dev=/dev/da0s1:volid=da0s1:fsname=msdosfs:type=usbdisk
dev=/dev/da0s2a:volid=nomadroot:fsname=ufs:type=usbdisk
dev=/dev/da0s3a:volid=nomadhome:fsname=ufs:type=usbdisk
dev=/dev/pseudo00:volid=gvfs:fsname=fuse:mntpt=/var/run/user/1001/gvfs:type=hdd

% dsbmc-cli -m /dev/da0s3a
````

**Comment by timsofteng** [comment]
> `dsbmc-cli -l`

It return nothing. However I put `dsbmc-cli -a&` into my `.xinitrc`

**Comment by mrclksr** [comment]
Could you please post the content of your `/etc/fstab`?

**Comment by timsofteng** [comment]
> Could you please post the content of your `/etc/fstab`?

Should I rewrite my `/etc/fstab` manually? I dint't do it. Inst't dsmbd do it automatically?

**Comment by mrclksr** [comment]
> Should I rewrite my /etc/fstab manually? 

No. DSBMD ignores any partition which has an /etc/fstab entry. That's why I asked for the content, because it's quite odd there is no devices listed. Could you please provide the output of `tail -50 /var/log/dsbmd.log`?

> Inst't dsmbd do it automatically?

Yes.

**Comment by timsofteng** [comment]
> tail -50 /var/log/dsbmd.log

Yep, sure.
Here is `tail -50 /var/log/dsbmd.log`

dsbmd: dsbmd started on Fri Sep 11 14:26:15 2020
dsbmd: ioctl(/dev/cd0, CDRIOCREADSPEED): Device not configured on Fri Sep 11 14:26:16 2020
dsbmd: Client with UID 1001 connected on Fri Sep 11 14:26:26 2020
mount_fusefs: failed to exec fuse daemon: No such file or directory
dsbmd: Device /dev/da0s1 mounted on /media/ventoy by UID 1001 on Fri Sep 11 14:26:42 2020
dsbmd: Device /dev/da0s2 mounted on /media/VTOYEFI by UID 1001 on Fri Sep 11 14:26:42 2020
dsbmd: Client with UID 1001 connected on Fri Sep 11 14:28:47 2020
dsbmd: Client with UID 1001 disconnected on Fri Sep 11 14:28:47 2020
dsbmd: Client with UID 1001 connected on Fri Sep 11 14:28:48 2020
dsbmd: Client with UID 1001 connected on Fri Sep 11 14:29:58 2020
dsbmd: Client with UID 1001 disconnected on Fri Sep 11 14:29:58 2020
dsbmd: Client with UID 1001 connected on Fri Sep 11 14:30:06 2020
dsbmd: Client with UID 1001 disconnected on Fri Sep 11 14:30:06 2020
mount_fusefs: failed to exec fuse daemon: No such file or directory
dsbmd: Device /dev/da0s1 mounted on /media/ventoy by UID 1001 on Fri Sep 11 14:43:05 2020
dsbmd: Device /dev/da0s2 mounted on /media/VTOYEFI by UID 1001 on Fri Sep 11 14:43:05 2020
dsbmd: write(): Broken pipe on Fri Sep 11 14:44:27 2020
dsbmd: dsbmd exited on Fri Sep 11 14:44:27 2020
dsbmd: dsbmd started on Fri Sep 11 15:47:53 2020
dsbmd: ioctl(/dev/cd0, CDRIOCREADSPEED): Device not configured on Fri Sep 11 15:47:54 2020
dsbmd: Client with UID 1001 connected on Fri Sep 11 15:54:04 2020
dsbmd: Client with UID 1001 connected on Fri Sep 11 18:01:47 2020
dsbmd: Client with UID 1001 disconnected on Fri Sep 11 18:01:47 2020
dsbmd: Client with UID 1001 connected on Fri Sep 11 18:02:47 2020
dsbmd: Client with UID 1001 disconnected on Fri Sep 11 18:02:47 2020
dsbmd: Client with UID 1001 connected on Fri Sep 11 18:12:01 2020
dsbmd: Client with UID 1001 disconnected on Fri Sep 11 18:12:01 2020
dsbmd: Client with UID 1001 connected on Fri Sep 11 18:12:04 2020
dsbmd: Client with UID 1001 disconnected on Fri Sep 11 18:12:04 2020
dsbmd: Client with UID 0 connected on Fri Sep 11 18:15:41 2020
dsbmd: Client with UID 0 disconnected on Fri Sep 11 18:15:41 2020

**Comment by timsofteng** [comment]
cat /etc/fstab

![image](https://user-images.githubusercontent.com/51912173/92948136-9a8a9580-f461-11ea-8c11-56497cec0b98.png)

**Comment by mrclksr** [comment]
Assuming your HDD/SSD is ada0, what does the following output?:
````
# sh -c 'for d in /dev/ada0p*; do fstyp $d; done'
````

**Comment by timsofteng** [comment]
> Assuming your HDD/SSD is ada0, what does the following output?:
> 
> ```
> # sh -c 'for d in /dev/ada0p*; do fstyp $d; done'
> ```

Should I insert my disk name here?
This is return nothing

 sh -c 'for d in diskid/DISK-WD-WCC2ER8VR457p0; do fstyp $d; done'
fstyp: diskid/DISK-WD-WCC2ER8VR457p0: No such file or directory

**Comment by mrclksr** [comment]
> Should I insert my disk name here?

The device name, like `ada0`. You can see it in the output of `glabel status`. Look for the line which matches `diskid/DISK-WD-WCC2ER8VR457`

**Comment by timsofteng** [comment]
> glabel status

![image](https://user-images.githubusercontent.com/51912173/92950581-95c7e080-f465-11ea-9841-c303f917926d.png)

**Comment by mrclksr** [comment]
Hmm, interesting ...

What does `ls /dev/ada0*` say?

**Comment by timsofteng** [comment]
> ls /dev/ada0*

Here is response
`/dev/ada0`

**Comment by mrclksr** [comment]
Now I understand why DSBMD doesn't show any devices. From your `gpart show` output I can see that your disk has a GPT layout, and has 8 partitions, but, and that is what confuses me, there are no `ada0p1`, ..., `ada0p8` device which represent those partitions. Can you still boot Linux and/or Windows from that disk?

**Comment by mrclksr** [comment]
Could you please provide the output of `gpart show -p ada0`?

**Comment by timsofteng** [comment]
Yep, I can boot linux and windows without any issues.

`gpart show -p ada0`
`gpart: No such geom: ada0.`

**Comment by mrclksr** [comment]
What about `gpart show -p` and `glabel status`?

**Comment by timsofteng** [comment]
gpart show -p
=>       34  976773101    diskid/DISK-WD-WCC2ER8VR457  GPT  (466G)
         34       2014                                 - free -  (1.0M)
       2048    1021952  diskid/DISK-WD-WCC2ER8VR457p1  ms-recovery  (499M)
    1024000     202752  diskid/DISK-WD-WCC2ER8VR457p2  efi  (99M)
    1226752      32768  diskid/DISK-WD-WCC2ER8VR457p3  ms-reserved  (16M)
    1259520  200704000  diskid/DISK-WD-WCC2ER8VR457p4  ms-basic-data  (96G)
  201963520  256870400  diskid/DISK-WD-WCC2ER8VR457p5  ms-basic-data  (122G)
  458833920  151744512                                 - free -  (72G)
  610578432  212916224  diskid/DISK-WD-WCC2ER8VR457p6  linux-data  (102G)
  823494656   33329152  diskid/DISK-WD-WCC2ER8VR457p7  linux-swap  (16G)
  856823808   52428800  diskid/DISK-WD-WCC2ER8VR457p8  freebsd-zfs  (25G)
  909252608   67520527                                 - free -  (32G)

**Comment by timsofteng** [comment]
glabel status
                       Name  Status  Components
diskid/DISK-WD-WCC2ER8VR457     N/A  ada0

**Comment by mrclksr** [comment]
Thank you for your patience. I will have to modify the source code to handle unusual cases like this. I will let you know so that you can test it.

**Comment by timsofteng** [comment]
> Thank you for your patience. I will have to modify the source code to handle unusual cases like this. I will let you know so that you can test it.

No problem. Thanks for fast support.

**Comment by mrclksr** [comment]
I did some research and found out that what's happening here is so called GEOM withering. If you mount a partition by its disk ID, the device nodes like `ada`, and `da` disappear. You can disable disk IDs by setting `kern.geom.label.disk_ident.enable="0"` in `/boot/loader.conf`, and reboot.

**Comment by timsofteng** [comment]
Looks like it works now.
But I have few more questions.

1. When I plug usb-stick and open it from pcmanfm file manager and then unplug usb pcmanfm closeb by itself. Is it a bug in file manager or in dsbmd?
2. Can i somehow open and modified partitions on my usb-stick which was burned with ventoy? Now i get error on opening.
Here is ventoy quick guide:
https://www.ventoy.net/en/doc_start.html

**Comment by mrclksr** [comment]
> Looks like it works now.

Excellent.

> But I have few more questions.
>   1. When I plug usb-stick and open it from pcmanfm file manager and then unplug usb pcmanfm closeb by itself. Is it a bug in file manager or in dsbmd?

This has nothing to do with DSBMD. It mounts the device, changes its permission, etc. Who or what opens the mount point is non of its business.

> 2. Can i somehow open and modified partitions on my usb-stick which was burned with ventoy? Now i get error on opening.
Here is ventoy quick guide:

Depending on the filesystem of the partition holding the ISO images, it is possible to mount an modify the content. In case of ExFAT you have to install [sysutils/fusefs-exfat](https://www.freshports.org/sysutils/fusefs-exfat) from ports.

**Comment by timsofteng** [comment]
> > Looks like it works now.
> 
> Excellent.
> 
> > But I have few more questions.
> > 
> > 1. When I plug usb-stick and open it from pcmanfm file manager and then unplug usb pcmanfm closeb by itself. Is it a bug in file manager or in dsbmd?
> 
> This has nothing to do with DSBMD. It mounts the device, changes its permission, etc. Who or what opens the mount point is non of its business.
> 
> > 1. Can i somehow open and modified partitions on my usb-stick which was burned with ventoy? Now i get error on opening.
> >    Here is ventoy quick guide:
> 
> Depending on the filesystem of the partition holding the ISO images, it is possible to mount an modify the content. In case of ExFAT you have to install [sysutils/fusefs-exfat](https://www.freshports.org/sysutils/fusefs-exfat) from ports.

Thank you very much.
Do you know why I can't install fusefs-exfat from pkg?

![image](https://user-images.githubusercontent.com/51912173/92996002-d9c3ef80-f510-11ea-85ab-e32bc0c5746b.png)

**Comment by mrclksr** [comment]
> Do you know why I can't install fusefs-exfat from pkg?

This is due to licensing issues. You have to acknowledge the Microsoft license.

**Comment by timsofteng** [comment]
> > Do you know why I can't install fusefs-exfat from pkg?
> 
> This is due to licensing issues. You have to acknowledge the Microsoft license.

Got it. Should i manually enable `fusefs_enable="YES"` in rc.conf after installing port?

**Comment by mrclksr** [comment]
>  Should i manually enable fusefs_enable="YES" in rc.conf after installing port?

This is not necessary. DSBMD should load the fusefs module automatically (check `kldstat | grep fuse`).

**Comment by timsofteng** [comment]
Ok. I'll test it soon.
Thanks!

**Comment by timsofteng** [comment]
I haven't install fusefs-exfat yet but I wanna say exfat usb sticks work out of box without it.
It just doesn't recognize ventoy second patition with iso's. There are two partitions as EFI and second for iso's. Dsbmd recognize just EFI.

**Comment by mrclksr** [comment]
> I haven't install fusefs-exfat yet but I wanna say exfat usb sticks work out of box without it.

If it's really exFAT, and you haven't installed fusefs-exfat, this is not possible. If DSBMD is asked to mount an exFAT partition, it executes `mount.exfat-fuse` (installed by sysutils/fusefs-exfat) via `/sbin/mount_fusefs`. It's probably a FAT or NTFS stick. You can see the filesystem type in the output of `dsbmc-cli -l`. What does the command show with your *ventoy* stick plugged in?

**Comment by timsofteng** [comment]
> > I haven't install fusefs-exfat yet but I wanna say exfat usb sticks work out of box without it.
> 
> If it's really exFAT, and you haven't installed fusefs-exfat, this is not possible. If DSBMD is asked to mount an exFAT partition, it executes `mount.exfat-fuse` (installed by sysutils/fusefs-exfat) via `/sbin/mount_fusefs`. It's probably a FAT or NTFS stick. You can see the filesystem type in the output of `dsbmc-cli -l`. What does the command show with your _ventoy_ stick plugged in?

Thank you for fast response and support.
I have added exfat module and ventoy multiboot usb works correct.
Looks like now everything is work like I expect.
