### ISSUE TITLE
DSBMD in FreeBSD 13.0

### ISSUE THREAD

**Issue by sinaps52ru** [mrclksr/DSBMD#7]
After upgrading to FreeBSD 13.0, I am unable to mount the USB stick a second time. After mounting and unmounting, the computer does not see it until the daemon is restarted.

**Comment by mrclksr** [comment]
Hi @sinaps52ru,

the problem was fixed in 1.11.4.

**Comment by sinaps52ru** [comment]
Ok. I am looking forward to the package dsbmd-1.11.4. At the moment in the repository for FreeBSD 13.0:amd64 only dsbmd-1.11.3. :(

**Comment by mrclksr** [comment]
Yes, unfortunately. But, there should soon be a package available, at least in *latest*. Alternatively, you can install 1.11.4 from ports.

**Comment by sinaps52ru** [comment]
I have too old laptop to build the port. I'll be waiting for the package.

**Comment by mrclksr** [comment]
You can also install from the latest source directly:
1. Download https://github.com/mrclksr/DSBMD/archive/refs/tags/1.11.4.tar.gz
2. `tar xf DSBMD-1.11.4.tar.gz`
3. `su`
4.  `cd DSBMD-1.11.4 && make install`

**Comment by sinaps52ru** [comment]
Thank you! It works!
